### ISSUE TITLE
What is the default username/password ?

### ISSUE THREAD

**Issue by coulix** [nectar-cs/mosaic#2]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/26057/70167066-3e226a80-16c6-11ea-9fe3-d9f66f1fbd81.png">

**Comment by coulix** [comment]
I tried nectar/nectar

**Comment by secops360** [comment]
I understand that u/p is outside of my K8S cluster, however I still can't register for a user?

**Comment by xavier-r-millot** [comment]
Oh you're on the login page :) Click on the Register page

**Comment by coulix** [comment]
Got it, the DISTURBING issue was the greyed button...
It seems to only accept password with [a-Z] + digits.
